### ISSUE TITLE
Deaths and Confirmed aren't good to distinguish

### ISSUE THREAD

**Issue by luap42** [stevenliuyi/covid19#1]
The colors for "Deaths" and "Confirmed" in the line chart aren't that good to distinguish.

For example on this screen shot for the UK:

![UK Covid19 cases](https://user-images.githubusercontent.com/21335202/75661352-6beb6100-5c6d-11ea-90c8-711a38ef5402.png)

It looks like the upper line are deaths (probably, because the light line is next to it), whereas it is supposed to be confirmed (no deaths yet). And hover doesn't work without a mouse/on mobile. This is an accessibility issue.

The colours should be updated to be more distinguishable. Futhermore it might be a good idea to order the labels in the legend in the way, that the one with the highest count is the first and then in descending order. This will make it even more clear.

**Comment by stevenliuyi** [comment]
Hi, I have changed the colors and the order of labels. As for the hover effect, it works on my iPhone when I touch the plot on the screen. Or do I misunderstand the issue?

**Comment by luap42** [comment]
Thanks. This seems to fix the issues.

With regards to no mouse, I was talking about using the keyboard. The problem was (or is? Can't test now) that there were many nodes, which resulted in requiring a lot of tabbing to get to that.
