### ISSUE TITLE
Update stopped on April 5th

### ISSUE THREAD

**Issue by rafaelsabino** [stevenliuyi/covid19#23]
Update stopped on April 5th. Does anyone know how to make the update work? I was unable to update after BUILD.

**Comment by stevenliuyi** [comment]
Hi! I'm not sure why there is no update after Apr 5. It works on my end. Probably it's the same issue as #21?

**Comment by rafaelsabino** [comment]
Thanks for the answer. I believe I need to configure a cron job on the server. How did you go about updating the data in certain periods?

**Comment by stevenliuyi** [comment]
I've been using GitHub Actions to update the data. You can check [the workflow file](https://github.com/stevenliuyi/covid19/blob/master/.github/workflows/datasest_updates.yml).

**Comment by estebaniglesias** [comment]
Hello. I'll answer the question you posed in #21 , here. I am able to see the updated data. In fact. all.json and all_minified.json happen to be updated!
The extrange thing is that (as in your website https://covid19.health/), the summary has stopped in 4 april :O. I tried to figured out if this was an issue with the package date-fsn, but not....

**Comment by rafaelsabino** [comment]
@stevenliuyi I loved your map. Very excellent, I would just like to make the update work. When I run the .sh files separately I am informed of an invalid path. I don't know how to run the stream file on a web server. How do you configure the update here on github?

**Comment by rafaelsabino** [comment]
@estebaniglesias how did you do to update your map? Are you running an external server too?

**Comment by rafaelsabino** [comment]
@estebaniglesias how did you do to update your map? Are you running an external server too?

**Comment by estebaniglesias** [comment]
Hello @rafaelsabino . Yes, and in my personal computer too :), I am not running GitHub actions, but pulling with a script (is the same, then) from the submodules. (--recursive is the key here). There are also other data that is being updated in the "install process"

**Comment by rafaelsabino** [comment]
@estebaniglesias thanks for responding, could you please send me the code you are using to run the script?

**Comment by estebaniglesias** [comment]
Hello @rafaelsabino . Well, the script has many more things of other projects.
But basically whta is doing is
```
git pull --recurse-submodules
yarn install
yarn build
serve -s build
```
Other instructions on how did I installed, in #22

**Comment by rafaelsabino** [comment]
Thank you very much @estebaniglesias , but whenever I run postinstall it sends me the error below. Did you go through this? It looks like you're playing a semicolon before turning.

`error C:\Users\Avell\COVID_19\node_modules\postinstall-postinstall: Command fai
led.
Exit code: 1
Command: node ./run.js
Arguments:
Directory: C:\Users\Avell\COVID_19\node_modules\postinstall-postinstall
Output:
No such package ;

  File not found: C:/Users/Avell/COVID_19/node_modules/**;**/package.json
error Command failed with exit code 1.
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn run postinstall
No such package ;

  File not found: C:/Users/Avell/COVID_19/node_modules/**;**/package.json
error Command failed with exit code 1.
`

**Comment by estebaniglesias** [comment]
Are you running all the commands in `C:\Users\Avell\COVID_19`?

**Comment by rafaelsabino** [comment]
That's right

**Comment by rafaelsabino** [comment]
@estebaniglesias I can perform the package installation and build. However no matter what I do the data never updates. They always have the same date on the image. I don't know how to update the data.
![Anotação 2020-04-07 115334](https://user-images.githubusercontent.com/12975702/78684355-bc865780-78c6-11ea-8e3c-3eac76498385.png)

**Comment by estebaniglesias** [comment]
Hello, congratulations! Igot the same issue! See here: #21 ! It happened that in Chile we moved to winter time the 4th April. Might it be that?

**Comment by stevenliuyi** [comment]
Have you tried to use `git submodule update --remote` to update all the submodules?

**Comment by stevenliuyi** [comment]
@rafaelsabino If you check `package.json`, the semicolon in `postinstall` is used to separate two commands. It's the syntax in Unix-like systems to run multiple commands sequentially. I'm not sure what's the correct way to do it in Windows, but you can just run the two commands separately.

Actually you may not need to run the second command (`postinstall.sh`) at all. This script is used to generate updated data and maps. Each time [the workflow](https://github.com/stevenliuyi/covid19/blob/master/.github/workflows/datasest_updates.yml) runs, updated data and maps are generated using `postinstall.sh` and then committed to this Github repo. So if you pull the latest version, the new data and maps should already be there.

**Comment by rafaelsabino** [comment]
I understand. Thank you very much @stevenliuyi for the clarifications. I'll try to do. But the question is, is there a way to let the server do this for me, like a cron job? Because there is no way for me to keep updating and generating builds every day. It would be interesting to be all automatic. The idea would be to run on a web server and update via cron. I don't intend to run on windows. On windows I'm just doing a test. By the way, I really loved your work. You are excellent in that area. It really won my admiration.

**Comment by estebaniglesias** [comment]
Hello @stevenliuyi , thank you so much for your support.
However, I don't think this is the same issue as in #21 . For example, if today 07. April I log in to https://covid19.health/ from my usual browser (Firefox in my case) in Chile (and several friends here have tried the same). I still see the main statistics for 04. April
![Screenshot 2020-04-07 14 41 25](https://user-images.githubusercontent.com/2274485/78706938-e72fda80-78dd-11ea-83ca-494a1dd7f789.png)

But if I log in from other location using the Tor Browser, I get the correct date.
![Screenshot 2020-04-07 14 44 58](https://user-images.githubusercontent.com/2274485/78707282-63c2b900-78de-11ea-9d2a-eaabc0feadaf.png)

So at least my issue is not about updated data.

**Comment by estebaniglesias** [comment]
If I change my location in my operative system to, let's say Germany, I got the correct date!
The problem is that I would like to use your app, particulary for Chilean users... I bet it might be something with the date-fns package?

**Comment by pescap** [comment]
Same issue, also in Chile. Attached I added a full print screen.

![chile](https://user-images.githubusercontent.com/14826266/78710208-efd6df80-78e2-11ea-97e9-a8e007b32e4c.png)

**Comment by stevenliuyi** [comment]
@rafaelsabino Thank you! You may use cron to run a script like this: (I haven't test it, so couldn't guarantee it works without issue.)

```
git pull --rebase
git submodule update --remote
yarn install
yarn build
```

**Comment by stevenliuyi** [comment]
@estebaniglesias @pescap Hi, I've already reproduced the issue when I change my timezone to Chile, and I think it's indeed related to the daylight saving time. I'm trying to find a solution.

**Comment by stevenliuyi** [comment]
@estebaniglesias @pescap Hopefully the issue is fixed by now.

**Comment by estebaniglesias** [comment]
I'll try now!

**Comment by estebaniglesias** [comment]
Hi @stevenliuyi , this defenetly solves the issue! Thanks a lot!

**Comment by rafaelsabino** [comment]
@stevenliuyi it seems to work the way you taught. I will continue to monitor to see if there are any problems with the updates. Another quick question, how do I change the American standard date view of graphics from (mm / dd) to (dd / mm)? In my country we see the day and after the month.

Thanks for all the support.

**Comment by estebaniglesias** [comment]
Hi @rafaelsabino, I got the solution! Give me a couple of hours and I can get into it.

**Comment by rafaelsabino** [comment]
Hi @stevenliuyi thanks, I'm waiting. I stay very grateful.

**Comment by rafaelsabino** [comment]
Hello @stevenliuyi, how are you? Did you get to see anything about the date?

**Comment by estebaniglesias** [comment]
Hi! @rafaelsabino , for me is Ok!

**Comment by rafaelsabino** [comment]
> @stevenliuyi it seems to work the way you taught. I will continue to monitor to see if there are any problems with the updates. Another quick question, how do I change the American standard date view of graphics from (mm / dd) to (dd / mm)? In my country we see the day and after the month.
> 
> Thanks for all the support.

Hello @estebaniglesias . I was referring to this question, about how to do this. The data is correct, I was just trying to change the date format of the graph because in my country we see (dd/mm) and not the American standard (mm/dd). The question was how to change that.

**Comment by estebaniglesias** [comment]
See in src/components/DateSlider.js and edit
function formatTick(ms) {
    return format(new Date(ms), 'M/d')
}
See https://date-fns.org/docs/Getting-Started
for more formats. For example, I have not got time to show the month in letters but in Spanish!
If you manage to do ir correctly (documentation in the link), please let me know!
;)

**Comment by rafaelsabino** [comment]
Thank you very much my friend for your help. I'll adjust it here and if I can, I'll tell you. Thanks

**Comment by stevenliuyi** [comment]
@estebaniglesias Thank you for your help!
@rafaelsabino Let me know if you still have problem modifying the format.

**Comment by rafaelsabino** [comment]
@stevenliuyi good night, how are you? How do I set the clear theme and table widget instead of the circle by default when loading the page?

**Comment by rafaelsabino** [comment]
@stevenliuyi I managed to adjust the settings. Now I would like to translate the names of the countries, but I couldn't. Even translating the i18n.yml file, the countries are still in English.

**Comment by estebaniglesias** [comment]
Hi

> @stevenliuyi good night, how are you? How do I set the clear theme and table widget instead of the circle by default when loading the page?

I encourage to look for specific key words on the repository.
I you look for "dark", you'll realize that this is in the variable darkMode
https://github.com/stevenliuyi/covid19/search?q=darkMode&unscoped_q=dark
Then, look for darkMode
https://github.com/stevenliuyi/covid19/search?q=darkMode&unscoped_q=darkMode

and you'll find the answer. change true to false in 
src/components/App.js

**Comment by rafaelsabino** [comment]
@estebaniglesias Thanks for the answer. I had found it before. My last question was about translating country names. The graph and table are always in the English language.

**Comment by estebaniglesias** [comment]
Hi. I don't think it is  a easy thing. My friend @pescap just commited a
pull request that was accepted adding new languages to the interface.

But having read the code, and how the data is taken, country names always
need names in English and in Chinesse. I thing what will better help you is
to open a new Issue about this topic, and we can continue discussing this
there! And will take the attention of others looking for the same. ;)

Le jeu. 16 avr. 2020 à 14:34, Rafael Sabino <notifications@github.com> a
écrit :

**Comment by rafaelsabino** [comment]
Okay, you're right. You will close this issue that has already been resolved and open another topic.
