### ISSUE TITLE
South America countries not appearing in MapNavBar

### ISSUE THREAD

**Issue by pescap** [stevenliuyi/covid19#33]
Hi!
South America countries are missing in the MapNavBar list:

![Capture d’écran 2020-04-16 à 12 11 16](https://user-images.githubusercontent.com/14826266/79480056-99049080-7fdb-11ea-9468-ac2e89c429f7.png)

Best wishes,

**Comment by stevenliuyi** [comment]
This should be fixed for now.

**Comment by pescap** [comment]
That's perfect, thank you!
