### ISSUE TITLE
[Not Issue/Just A Question] - No New Update Lately?

### ISSUE THREAD

**Issue by erlange** [stevenliuyi/covid19#37]
Hello, Steven

It's been quite no fresh data update lately
I wonder if something's wrong

Cheers,

**Comment by stevenliuyi** [comment]
Hello! I have fixed some issues preventing data updates, and the site should be updated by now.

**Comment by erlange** [comment]
> 
> 
> Hello! I have fixed some issues preventing data updates, and the site should be updated by now.

Thanks mate.
Stay safe & healthy.

Cheers
