### ISSUE TITLE
Change reference repo for Regions/France data

### ISSUE THREAD

**Issue by pescap** [stevenliuyi/covid19#40]
Dear @stevenliuyi,
Repository for Regions in France seems outdated and is giving wrong results. France being one of the most critical countries, it would be interesting to provide the most refreshed information.

The official French repository is the following:
https://github.com/opencovid19-fr/

Output data files are available in x=json or x=csv at:
https://github.com/opencovid19-fr/data/raw/master/dist/chiffres-cles.x

FYI:  chiffres-cles goes with:
"date"
"nom" => RegionName ("France" is also included)
"casConfirmes" => Confirmed Cases
"deces" => Deaths
"gueris" => Recovered

I don't know which format is the most useful to process the information and embed it into data_processing.js.

Besides, the official French Government dashboard is available at:
https://github.com/etalab/covid19-dashboard

It has a script "prepare-data.js".

Can I help you with this?
Best wishes,
Paul

**Comment by stevenliuyi** [comment]
After investigating the repos, it seems that France had stopped reporting number of confirmed cases for regions, instead they are only reporting number of hospitalized cases.
