### ISSUE TITLE
Feature request: controlling time range of plots

### ISSUE THREAD

**Issue by vbrik** [stevenliuyi/covid19#6]
Firstly, I find https://covid19.health/ to be the most useful covid19 visualization site for me. Thanks very much for making it available!

It would be great if it was possible to zoom in to a particular time range in the plots. For example, the first non-zero data point for Wisconsin is 3/10, but the cases plot starts from 1/22, so non-zero part of the curves is very compressed

**Comment by stevenliuyi** [comment]
Hello! I have just added support for controlling time range. Now after you click the "full screen" icon for the plots, you'll be able to change the time range using the slider in the bottom.

**Comment by vbrik** [comment]
Thanks very much!
